const ENTER_KEY_PRESS = '\uE007';
const ESCAPE_KEY_PRESS = '\ue00C';
const BACKSPACE_KEY_PRESS = '\uE003';
const CONTROL_KEY_PRESS = '\ue009';

module.exports = {
  ENTER_KEY_PRESS: ENTER_KEY_PRESS,
  ESCAPE_KEY_PRESS: ESCAPE_KEY_PRESS,
  BACKSPACE_KEY_PRESS: BACKSPACE_KEY_PRESS,
  CONTROL_KEY_PRESS: CONTROL_KEY_PRESS
};
